"""H5 learner state and shared teaching variants; additive migration."""
from alembic import op
import sqlalchemy as sa
revision = '20260929_0014'
down_revision = '20260927_0013'
branch_labels = depends_on = None

def upgrade():
    op.alter_column('jobs', 'batch_id', existing_type=sa.Uuid(), nullable=True)
    op.execute('\nCREATE TABLE learning_sessions (\n\tid UUID NOT NULL, \n\tuser_id UUID NOT NULL, \n\tsubject_id UUID NOT NULL, \n\tsource VARCHAR(30) NOT NULL, \n\ttitle VARCHAR(200) NOT NULL, \n\tquestion_ids JSONB NOT NULL, \n\tposition INTEGER NOT NULL, \n\tdrafts JSONB NOT NULL, \n\tattempts JSONB NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(user_id) REFERENCES users (id), \n\tFOREIGN KEY(subject_id) REFERENCES exam_subjects (id)\n)\n\n')
    op.execute('CREATE INDEX ix_learning_sessions_user_id ON learning_sessions (user_id)')
    op.execute('\nCREATE TABLE user_exam_plans (\n\tuser_id UUID NOT NULL, \n\tsubject_id UUID NOT NULL, \n\ttitle VARCHAR(100) NOT NULL, \n\texam_date DATE NOT NULL, \n\tstart_date DATE NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (user_id, subject_id), \n\tFOREIGN KEY(user_id) REFERENCES users (id), \n\tFOREIGN KEY(subject_id) REFERENCES exam_subjects (id)\n)\n\n')
    op.execute('\nCREATE TABLE user_learning_preferences (\n\tuser_id UUID NOT NULL, \n\tsubject_id UUID, \n\tmotto VARCHAR(200) NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (user_id), \n\tFOREIGN KEY(user_id) REFERENCES users (id), \n\tFOREIGN KEY(subject_id) REFERENCES exam_subjects (id)\n)\n\n')
    op.execute('\nCREATE TABLE teaching_variants (\n\tid UUID NOT NULL, \n\tsubject_id UUID NOT NULL, \n\tnode_id UUID NOT NULL, \n\tmatch_key VARCHAR(64) NOT NULL, \n\tcontent_hash VARCHAR(64) NOT NULL, \n\tstatus VARCHAR(20) NOT NULL, \n\tcontent JSONB NOT NULL, \n\tmodel VARCHAR(200) NOT NULL, \n\tprompt_version VARCHAR(64) NOT NULL, \n\tvalidation JSONB NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(subject_id) REFERENCES exam_subjects (id), \n\tFOREIGN KEY(node_id) REFERENCES knowledge_nodes (id), \n\tUNIQUE (content_hash)\n)\n\n')
    op.execute('CREATE INDEX ix_teaching_variants_match_key ON teaching_variants (match_key)')
    op.execute('\nCREATE TABLE teaching_variant_answers (\n\tuser_id UUID NOT NULL, \n\tvariant_id UUID NOT NULL, \n\tanswer VARCHAR(10) NOT NULL, \n\tcorrect BOOLEAN NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (user_id, variant_id), \n\tFOREIGN KEY(user_id) REFERENCES users (id), \n\tFOREIGN KEY(variant_id) REFERENCES teaching_variants (id)\n)\n\n')
    op.execute('\nCREATE TABLE teaching_variant_reports (\n\tid UUID NOT NULL, \n\tuser_id UUID NOT NULL, \n\tvariant_id UUID NOT NULL, \n\treason VARCHAR(1000) NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(user_id) REFERENCES users (id), \n\tFOREIGN KEY(variant_id) REFERENCES teaching_variants (id)\n)\n\n')
    op.execute('\nCREATE TABLE tutor_sessions (\n\tid UUID NOT NULL, \n\tuser_id UUID NOT NULL, \n\tquestion_id UUID NOT NULL, \n\tattempt_id UUID, \n\tcontext JSONB NOT NULL, \n\tprompt_version VARCHAR(64) NOT NULL, \n\tsystem_prompt TEXT NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(user_id) REFERENCES users (id), \n\tFOREIGN KEY(question_id) REFERENCES practice_questions (id), \n\tFOREIGN KEY(attempt_id) REFERENCES learning_attempts (id)\n)\n\n')
    op.execute('CREATE INDEX ix_tutor_sessions_user_id ON tutor_sessions (user_id)')
    op.execute('\nCREATE TABLE user_question_marks (\n\tuser_id UUID NOT NULL, \n\tquestion_id UUID NOT NULL, \n\tkind VARCHAR(20) NOT NULL, \n\tactive BOOLEAN NOT NULL, \n\tattempt_id UUID, \n\tresolved_at TIMESTAMP WITH TIME ZONE, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (user_id, question_id, kind), \n\tFOREIGN KEY(user_id) REFERENCES users (id), \n\tFOREIGN KEY(question_id) REFERENCES practice_questions (id), \n\tFOREIGN KEY(attempt_id) REFERENCES learning_attempts (id)\n)\n\n')
    op.execute('CREATE INDEX ix_mark_user_active_kind ON user_question_marks (user_id, active, kind)')
    op.execute('\nCREATE TABLE tutor_messages (\n\tid UUID NOT NULL, \n\tsession_id UUID NOT NULL, \n\trole VARCHAR(20) NOT NULL, \n\tcontent TEXT NOT NULL, \n\tjob_id UUID, \n\tvariant_id UUID, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_tutor_job_role UNIQUE (job_id, role), \n\tFOREIGN KEY(session_id) REFERENCES tutor_sessions (id), \n\tFOREIGN KEY(job_id) REFERENCES jobs (id), \n\tFOREIGN KEY(variant_id) REFERENCES teaching_variants (id)\n)\n\n')
    op.execute('CREATE INDEX ix_tutor_messages_session_id ON tutor_messages (session_id)')
    op.execute("INSERT INTO user_question_marks (user_id, question_id, kind, active, attempt_id, created_at, updated_at)\nSELECT DISTINCT ON (a.user_id, a.practice_question_id) a.user_id, a.practice_question_id, 'wrong', true, a.id, a.created_at, a.created_at\nFROM learning_attempts a WHERE EXISTS (SELECT 1 FROM learning_attempt_parts p WHERE p.attempt_id=a.id AND p.correct=false)\nORDER BY a.user_id, a.practice_question_id, a.created_at DESC, a.id DESC")

def downgrade():
    raise RuntimeError("Restore a paired backup; refusing to discard learning history")
